export const all_skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Figma",
  "Leadership",
  "Python",
];

export const all_languages = ["English", "Spanish", "French", "German", "Chinese"];

export const all_careers = [
  "Biología",
  "Biotecnología",
  "Bioquímica",
  "Ciencias Ambientales",
  "Ciencias de la Computación",
  "Ciencias Físicas",
  "Ciencias Matemáticas",
  "Estadística",
  "Genética",
  "Microbiología",
  "Química",
  "Geología",
  "Geofísica",
  "Ingeniería de Sistemas",
  "Ingeniería de Software",
  "Ingeniería Informática",
  "Ciencia de Datos",
  "Ciberseguridad",
  "Inteligencia Artificial",
  "Ingeniería Civil",
  "Ingeniería Industrial",
  "Ingeniería Mecánica",
  "Ingeniería Electrónica",
  "Ingeniería Eléctrica",
  "Ingeniería Química",
  "Ingeniería de Telecomunicaciones",
  "Ingeniería de Minas",
  "Ingeniería Ambiental",
  "Ingeniería Biomédica",
  "Matemáticas",
  "Física",
  "Bioinformática",
  "Nanotecnología",
  "Arquitectura",
  "Tecnología Médica",
  "Otro",
];